cell: ""
region: ""
storage:
  className: lites-nats-gp3-encrypted
  kmsKeyId: ""
externalSecret:
  refreshInterval: 1h
  store:
    kind: ClusterSecretStore
    name: ""
  remoteKey: ""
namespaces:
  application: lites
  data: data-system
  monitoring: observability
  dns: kube-system
dnsPodLabels:
  k8s-app: kube-dns
