"use client";

import Link from "next/link";
import { ArrowRight, CheckCircle2, Circle, FolderKanban, Plus } from "lucide-react";
import type { Locale } from "@/i18n/config";
import { demoMode } from "@/lib/demo";
import { demoMission, demoProjects } from "@/lib/model";
import { useProductWorkspace } from "@/lib/use-product-workspace";
import { WorkspaceLoadError } from "./workspace-load-error";

export function GoalsWorkspace({ locale }: { locale: Locale }) {
  const zh = locale === "zh-CN";
  const workspace = useProductWorkspace(locale, !demoMode);
  const focus = workspace.missions.focus;
  const focusName = focus ? workspace.missions.roleNames.get(focus.target_role_profile_id) ?? `${zh ? "成长目标" : "Mission"} ${focus.id.slice(0, 8)}` : "";
  const route = workspace.route?.route;
  return <div className="page-wrap"><header className="page-head"><div><p className="eyebrow">{zh ? "成长目标" : "Goals & projects"}</p><h1>{demoMode ? demoMission.name : focusName || (zh ? "还没有 Focus Mission" : "No Focus Mission yet")}</h1><p>{demoMode ? `${demoMission.path} · ${demoMission.stage}` : route?.summary ?? (zh ? "创建 Mission 后，路线、任务、项目和证据都将绑定到同一 Focus。" : "Create a Mission to bind route, tasks, projects, and evidence to one Focus.")}</p></div><Link className="button primary" href={`/${locale}/onboarding?new=mission`}><Plus />{zh ? "新建 Mission" : "New Mission"}</Link></header>
    {!demoMode && workspace.error && <WorkspaceLoadError locale={locale} message={workspace.error} loading={workspace.loading} onRetry={workspace.retry} />}
    {!demoMode && <section className="mission-overview card"><div><p className="section-label">{zh ? "全部 Missions" : "All Missions"}</p><h2>{workspace.missions.items.length} {zh ? "个目标" : "goals"}</h2><div className="milestone-list">{workspace.missions.items.map((mission) => <div key={mission.id}>{mission.focused || mission.id === workspace.missions.focusState.mission_id ? <CheckCircle2 /> : <Circle />}<span>{workspace.missions.roleNames.get(mission.target_role_profile_id) ?? mission.id.slice(0, 8)}</span><small>{mission.status} · v{mission.version}</small></div>)}</div></div><div className="mission-stage"><span>{focus?.current_route_revision_id ? (zh ? "当前路线已激活" : "Current route active") : (zh ? "等待路线接受" : "Awaiting route acceptance")}</span>{route && <><div className="progress-track"><span style={{ width: `${100 / route.stages.length}%` }} /></div><small>{route.stages[0]?.title}</small></>}</div></section>}
    {demoMode && <section className="mission-overview card"><div><p className="section-label">{zh ? "当前 Mission" : "Current Mission"}</p><h2>{zh ? "用生产级项目验证 Cloud Agent 能力" : "Prove cloud-agent capability through production-grade projects"}</h2><p>{zh ? "成功不是完成课程，而是产出可运行、可评审、可追溯的工作。" : "Success is not finishing content. It is producing runnable, reviewable, traceable work."}</p></div><div className="mission-stage"><span>Stage 1 / 4</span><div className="progress-track"><span style={{ width: "25%" }} /></div></div></section>}
    <div className="section-title"><div><p className="section-label">Workspace</p><h2>{zh ? "项目与里程碑" : "Projects and milestones"}</h2></div><Link className="button" href={`/${locale}/create`}><Plus />{zh ? "创建项目" : "Create project"}</Link></div>
    <section className="project-grid">{demoMode ? demoProjects.map((project) => <article className="project-card card" key={project.id}><header><span className="project-kind"><FolderKanban />{project.kind}</span></header><h3>{project.title}</h3><div className="milestone-list">{project.milestones.map((milestone) => <div key={milestone.name}>{milestone.status === "verified" ? <CheckCircle2 /> : <Circle />}<span>{milestone.name}</span><small>{milestone.status.replace("_", " ")}</small></div>)}</div><Link className="inline-link" href={`/${locale}/create`}>{zh ? "打开 Workspace" : "Open Workspace"}<ArrowRight /></Link></article>) : workspace.loading ? <article className="card">{zh ? "正在读取项目…" : "Loading projects…"}</article> : workspace.projects.length ? workspace.projects.map((project) => <article className="project-card card" key={project.id}><header><span className="project-kind"><FolderKanban />{project.project_kind}</span><span className="chip">{project.status}</span></header><h3>{project.title}</h3><div className="milestone-list"><div><CheckCircle2 /><span>Project revision</span><small>v{project.version}</small></div><div>{project.completed_at ? <CheckCircle2 /> : <Circle />}<span>{zh ? "完成与复盘" : "Completion & reflection"}</span><small>{project.completed_at ? new Intl.DateTimeFormat(locale, { dateStyle: "medium" }).format(new Date(project.completed_at)) : (zh ? "进行中" : "in progress")}</small></div></div><Link className="inline-link" href={`/${locale}/create?project=${encodeURIComponent(project.id)}`}>{zh ? "打开 Workspace" : "Open Workspace"}<ArrowRight /></Link></article>) : <article className="card"><h3>{zh ? "还没有项目" : "No projects yet"}</h3><p>{zh ? "从已接受路线创建代码、文字或设计项目。" : "Create a code, writing, or design project from an accepted route."}</p></article>}</section>
  </div>;
}
