import { ExternalLink, Scale, ShieldCheck } from "lucide-react";
import type { Locale } from "@/i18n/config";

export function LegalNotice({ locale }: { locale: Locale }) {
  const zh = locale === "zh-CN";
  return <div className="trust-page"><header className="public-hero"><p className="eyebrow">Legal notice</p><h1>{zh ? "开放源代码，保留清晰边界。" : "Open source, with clear boundaries."}</h1><p>{zh ? "Lites Community 以 GNU AGPL 3.0 only 发布。商业许可、商标、托管服务与支持必须由单独书面协议授予。" : "Lites Community is distributed under GNU AGPL 3.0 only. Commercial licensing, trademarks, hosted service, and support require separate written terms."}</p></header>
    <section className="trust-grid" aria-label={zh ? "法律说明" : "Legal notices"}><article className="card"><Scale aria-hidden="true" /><h2>{zh ? "源代码与许可" : "Source and licence"}</h2><p>{zh ? "你可以依照 AGPL-3.0 查看、运行、修改和再分发 Community 代码。通过网络提供修改版本时，必须向使用者提供对应源代码。" : "You may inspect, run, modify, and redistribute the Community code under AGPL-3.0. If you provide a modified version over a network, you must offer its corresponding source to those users."}</p><p><a href="https://github.com/erweixin/langshift.dev" rel="noreferrer" target="_blank">{zh ? "获取对应源代码" : "Get corresponding source"} <ExternalLink aria-hidden="true" /></a></p></article><article className="card"><ShieldCheck aria-hidden="true" /><h2>{zh ? "免责声明" : "No warranty"}</h2><p>{zh ? "在适用许可与法律允许的最大范围内，本软件不提供任何担保。安全与合规声明仅限 Trust Center 明确列出的当前证据。" : "The software is provided without warranty to the maximum extent allowed by its licence and applicable law. Security and compliance claims are limited to the current evidence explicitly listed in the Trust Center."}</p></article><article className="card"><Scale aria-hidden="true" /><h2>{zh ? "商标与商业权利" : "Trademark and commercial rights"}</h2><p>{zh ? "开源许可不授予 Lites 名称或标志的商标权，也不自动包含私有化商业许可、SLA 或支持。修改版必须清楚标明来源与变更。" : "The open-source licence does not grant trademark rights in the Lites name or marks and does not include private commercial licensing, an SLA, or support. Modified distributions must identify their origin and changes."}</p></article></section>
    <section className="trust-contact card"><ShieldCheck aria-hidden="true" /><div><p className="section-label">Documents</p><h2>{zh ? "治理材料随源代码发布" : "Governance materials ship with the source"}</h2><p>LICENSE · NOTICE · CLA.md · CONTRIBUTING.md · TRADEMARKS.md · SECURITY.md</p></div></section></div>;
}
