import { CheckCircle2, Cloud, DatabaseZap, EyeOff, FileCheck2, KeyRound, Scale, ServerCog, ShieldCheck, UsersRound } from "lucide-react";
import type { Locale } from "@/i18n/config";

const controls = [
  { icon: UsersRound, en: ["Tenant isolation", "Gateway-derived tenant and role context, PostgreSQL forced RLS, and exact service identities. Browser-supplied tenant or role claims are ignored."], zh: ["租户隔离", "租户与角色上下文由 Gateway 解析，PostgreSQL 强制 RLS，并使用精确服务身份。浏览器提交的 tenant 或 role 声明不会被信任。"] },
  { icon: KeyRound, en: ["Secrets and credentials", "Passwords use Argon2id. Session, reset, verification, invitation, BYOK, and signing material are stored as hashes or in a secret manager; plaintext credentials are not logged."], zh: ["密钥与凭据", "密码使用 Argon2id。Session、重置、验证、邀请、BYOK 与签名材料以哈希或 Secret Manager 形式保存；明文凭据不会进入日志。"] },
  { icon: DatabaseZap, en: ["Encrypted restricted content", "Support content, prompts, evidence, reflections, workspace data, and idempotency responses use envelope encryption and content-addressed immutable objects."], zh: ["受限内容加密", "支持工单、Prompt、证据、复盘、Workspace 数据与幂等响应使用信封加密和内容寻址的不可变对象。"] },
  { icon: ServerCog, en: ["Agent execution controls", "Durable state machines, leases and fences, effect ledgers, explicit approvals, reconciliation, and isolated Linux execution prevent duplicate or ungoverned effects."], zh: ["Agent 执行控制", "持久状态机、lease/fence、effect ledger、显式审批、对账与隔离的 Linux 执行环境用于防止重复或未治理副作用。"] },
  { icon: EyeOff, en: ["Enterprise privacy", "Private content is not exposed to employers by default. Reviewer access requires an explicit share grant; analytics are catalog-bound, budgeted, and suppress cells and complements below k=5."], zh: ["企业隐私", "私密内容默认不向企业暴露。Reviewer 访问必须有显式 share grant；聚合分析受 catalog 与预算约束，并对人数及补集小于 k=5 的结果稳定 suppression。"] },
  { icon: Cloud, en: ["Delivery and supply chain", "Production artifacts are digest-pinned, SBOM-backed, signed, provenance-attested, non-root, and deployable through Helm/OpenTofu or the private delivery bundle."], zh: ["交付与供应链", "生产制品锁定 digest，附带 SBOM、签名与来源证明，以 non-root 运行，并通过 Helm/OpenTofu 或私有化交付包部署。"] },
] as const;

export function TrustCenter({ locale }: { locale: Locale }) {
  const zh = locale === "zh-CN";
  return <div className="trust-page"><header className="public-hero"><p className="eyebrow">Trust Center</p><h1>{zh ? "信任来自可验证的边界。" : "Trust comes from verifiable boundaries."}</h1><p>{zh ? "这里公开 Lites 当前实现的安全、隐私、可靠性与治理控制。只陈述已有工程证据支持的事实；没有完成独立认证的事项会明确标注。" : "This page describes the security, privacy, reliability, and governance controls implemented by Lites. We state only what current engineering evidence supports and label independent certifications that have not been completed."}</p><div className="trust-badges"><span><ShieldCheck aria-hidden="true" />{zh ? "默认私密" : "Private by default"}</span><span><FileCheck2 aria-hidden="true" />{zh ? "可审计变更" : "Auditable change"}</span><span><Scale aria-hidden="true" />{zh ? "禁止权益决策" : "No employment decisions"}</span></div></header>
    <section className="trust-controls" aria-labelledby="trust-controls-title"><div className="public-section-head"><p className="section-label">{zh ? "控制" : "Controls"}</p><h2 id="trust-controls-title">{zh ? "纵深防御，而不是单点承诺" : "Defense in depth, not a single promise"}</h2></div><div className="trust-grid">{controls.map(({ icon: Icon, en, zh: chinese }) => { const text = zh ? chinese : en; return <article className="card" key={text[0]}><Icon aria-hidden="true" /><h3>{text[0]}</h3><p>{text[1]}</p></article>; })}</div></section>
    <section className="trust-principles"><div><p className="section-label">{zh ? "数据治理" : "Data governance"}</p><h2>{zh ? "用户证据不等于企业评分" : "User evidence is not an employer score"}</h2><p>{zh ? "Lites 不用于招聘筛选、晋升、解雇、员工排名、自动任务分配或其他影响职业权益的决定。能力声明必须绑定证据；删除、纠正、争议与撤回会创建新的可追溯 revision，不会静默改写历史。" : "Lites is not for hiring screening, promotion, termination, employee ranking, automated work assignment, or other employment-rights decisions. Capability claims must cite evidence; deletion, correction, dispute, and withdrawal create traceable revisions rather than silently rewriting history."}</p></div><ul><li><CheckCircle2 aria-hidden="true" />{zh ? "对话、复盘、证据与作品默认为 private" : "Conversations, reflections, evidence, and work are private by default"}</li><li><CheckCircle2 aria-hidden="true" />{zh ? "跨租户内容只能显式导出/导入复制" : "Cross-tenant content moves only through explicit export/import copying"}</li><li><CheckCircle2 aria-hidden="true" />{zh ? "导出与删除请求具有持久状态和审计证据" : "Export and erasure requests have durable state and audit evidence"}</li><li><CheckCircle2 aria-hidden="true" />{zh ? "管理员敏感读取必须说明理由并记录哈希" : "Sensitive administrator reads require a reason and record its hash"}</li></ul></section>
    <section className="trust-assurance"><div className="public-section-head"><p className="section-label">Assurance</p><h2>{zh ? "认证与独立验证状态" : "Certification and independent verification status"}</h2><p>{zh ? "安全控制已经进入自动化门禁，不等同于第三方认证。以下状态刻意避免把内部测试表述成外部背书。" : "Security controls are covered by automated gates, which is not the same as third-party certification. These statuses deliberately avoid presenting internal testing as external endorsement."}</p></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>{zh ? "项目" : "Program"}</th><th>{zh ? "当前声明" : "Current claim"}</th><th>{zh ? "证据边界" : "Evidence boundary"}</th></tr></thead><tbody><tr><td>SOC 2 Type II</td><td><span className="chip">{zh ? "未声明" : "Not claimed"}</span></td><td>{zh ? "尚无独立审计报告" : "No independent audit report is claimed"}</td></tr><tr><td>ISO 27001</td><td><span className="chip">{zh ? "未声明" : "Not claimed"}</span></td><td>{zh ? "尚无认证证书" : "No certification is claimed"}</td></tr><tr><td>{zh ? "渗透测试" : "Penetration test"}</td><td><span className="chip">{zh ? "GA 前必须完成" : "Required before GA"}</span></td><td>{zh ? "完成并批准前不会标为通过" : "Not represented as passed until completed and approved"}</td></tr><tr><td>{zh ? "供应链证明" : "Supply-chain evidence"}</td><td><span className="chip">{zh ? "自动化" : "Automated"}</span></td><td>SBOM · signature · provenance · digest pinning</td></tr></tbody></table></div></section>
    <section className="trust-contact card"><ShieldCheck aria-hidden="true" /><div><p className="section-label">{zh ? "安全报告" : "Security reports"}</p><h2>{zh ? "请不要在普通工单中提交可利用细节。" : "Do not put exploitable details in a routine support case."}</h2><p>{zh ? "请使用 GitHub 私密漏洞报告通道，并遵循 SECURITY.md 的数据最小化、研究边界、响应目标和协调披露流程。Lites 尚未声明公开漏洞奖励计划。" : "Use GitHub private vulnerability reporting and follow the data-minimization, research-boundary, response-target, and coordinated-disclosure process in SECURITY.md. Lites does not claim a public bug-bounty program."}</p></div></section>
  </div>;
}
