import { TranslationKeys } from "@/messages";

export const getCourses = (t: TranslationKeys) => ([
  {
    name: 'js2py',
    title: t.home.courses.js2py.title,
    description: t.home.courses.js2py.description,
    features: t.home.courses.js2py.features,
    duration: t.home.courses.js2py.duration,
    level: t.home.courses.js2py.level,
    icon: '🐍',
    color: 'from-green-500 to-emerald-600',
    bgColor: 'bg-green-500/10',
    borderColor: 'border-green-500/20',
    gradient: 'from-green-400/20 to-emerald-500/20',
  },
  {
    name: 'js2rust',
    title: t.home.courses.js2rust.title,
    description: t.home.courses.js2rust.description,
    features: t.home.courses.js2rust.features,
    duration: t.home.courses.js2rust.duration,
    level: t.home.courses.js2rust.level,
    icon: '🦀',
    color: 'from-orange-500 to-red-600',
    bgColor: 'bg-orange-500/10',
    borderColor: 'border-orange-500/20',
    gradient: 'from-orange-400/20 to-red-500/20',
  },
  {
    name: 'js2cpp',
    title: t.home.courses.js2cpp.title,
    description: t.home.courses.js2cpp.description,
    features: t.home.courses.js2cpp.features,
    duration: t.home.courses.js2cpp.duration,
    level: t.home.courses.js2cpp.level,
    icon: '🚀',
    color: 'from-blue-500 to-indigo-600',
    bgColor: 'bg-blue-500/10',
    borderColor: 'border-blue-500/20',
    gradient: 'from-blue-400/20 to-indigo-500/20',
  },
  {
    name: 'js2go',
    title: t.home.courses.js2go.title,
    description: t.home.courses.js2go.description,
    features: t.home.courses.js2go.features,
    duration: t.home.courses.js2go.duration,
    level: t.home.courses.js2go.level,
    icon: '🐹',
    color: 'from-cyan-500 to-blue-600',
    bgColor: 'bg-cyan-500/10',
    borderColor: 'border-cyan-500/20',
    gradient: 'from-cyan-400/20 to-blue-500/20',
  },
  {
    name: 'js2swift',
    title: t.home.courses.js2swift.title,
    description: t.home.courses.js2swift.description,
    features: t.home.courses.js2swift.features,
    duration: t.home.courses.js2swift.duration,
    level: t.home.courses.js2swift.level,
    icon: '🍎',
    color: 'from-pink-500 to-purple-600',
    bgColor: 'bg-pink-500/10',
    borderColor: 'border-pink-500/20',
    gradient: 'from-pink-400/20 to-purple-500/20',
  },
  {
    name: 'js2c',
    title: t.home.courses.js2c.title,
    description: t.home.courses.js2c.description,
    features: t.home.courses.js2c.features,
    duration: t.home.courses.js2c.duration,
    level: t.home.courses.js2c.level,
    icon: '⚙️',
    color: 'from-gray-500 to-slate-600',
    bgColor: 'bg-gray-500/10',
    borderColor: 'border-gray-500/20',
    gradient: 'from-gray-400/20 to-slate-500/20',
  },
  {
    name: 'js2kotlin',
    title: t.home.courses.js2kotlin.title,
    description: t.home.courses.js2kotlin.description,
    features: t.home.courses.js2kotlin.features,
    duration: t.home.courses.js2kotlin.duration,
    level: t.home.courses.js2kotlin.level,
    icon: '🟣',
    color: 'from-purple-500 to-violet-600',
    bgColor: 'bg-purple-500/10',
    borderColor: 'border-purple-500/20',
    gradient: 'from-purple-400/20 to-violet-500/20',
  },
  {
    name: 'py2js',
    title: t.home.courses.py2js.title,
    description: t.home.courses.py2js.description,
    features: t.home.courses.py2js.features,
    duration: t.home.courses.py2js.duration,
    level: t.home.courses.py2js.level,
    icon: '⚡',
    color: 'from-yellow-500 to-amber-600',
    bgColor: 'bg-yellow-500/10',
    borderColor: 'border-yellow-500/20',
    gradient: 'from-yellow-400/20 to-amber-500/20',
  },
  {
    name: 'js2java',
    title: t.home.courses.js2java.title,
    description: t.home.courses.js2java.description,
    features: t.home.courses.js2java.features,
    duration: t.home.courses.js2java.duration,
    level: t.home.courses.js2java.level,
    icon: '☕',
    color: 'from-red-500 to-orange-600',
    bgColor: 'bg-red-500/10',
    borderColor: 'border-red-500/20',
    gradient: 'from-red-400/20 to-orange-500/20',
  },
]);