/* This file is generated by scripts/typegen.mjs. Do not edit manually. */

/**
 * POST /api/content-generation-runs 与 GET /api/content-generation-runs/{run_id} 的公开 run 投影。
 */
export interface ContentGenerationRun {
  run_id: string;
  status:
    | "accepted"
    | "queued"
    | "executing"
    | "waiting_tool"
    | "waiting_approval"
    | "succeeded"
    | "failed"
    | "expired"
    | "cancelled";
  content_key?: string;
  cache_hit?: boolean;
  error?: {
    code?: string;
    message?: string;
    [k: string]: any;
  };
}
