/* This file is generated by scripts/typegen.mjs. Do not edit manually. */

/**
 * POST /api/content-generation-runs 的请求体。它是内容生成调试入口的稳定契约，正式 task-scoped 入口会复用同一组维度。
 */
export interface ContentGenerationInput {
  task_id?: string;
  task_template_id: string;
  target_stack: string;
  level_band: string;
  title: string;
  judge: string;
  minutes?: number;
  context?: {
    [k: string]: any;
  };
}
