/* This file is generated by scripts/typegen.mjs. Do not edit manually. */

/**
 * 课程内容定稿的存储与定稿校验契约（完整版）。两点注意：① 下发客户端的是剥离 exercise.reference_solution 后的投影（见 docs/exercise-runtime.md）；② 生成侧 structured output 使用本 schema 的简化投影（structured outputs 不支持 contains 等关键字），judge 覆盖与「测试必须挂掉起始代码」由管线校验步骤强制（docs/content-pipeline.md 校验 #2/#3），本 schema 在定稿写入前做最终把关。
 */
export interface ContentArtifact {
  schema_version: number;
  /**
   * hash(task_template_id, target_stack, level_band, content_version, prompt_version)
   */
  content_key: string;
  /**
   * 如 fe2agent-d01，见 docs/curriculum-14d.md
   */
  task_template_id: string;
  /**
   * 参与 content_key 计算，必填
   */
  target_stack: string;
  level_band: string;
  content_version: number;
  prompt_version: number;
  lesson: {
    title: string;
    minutes: number;
    /**
     * 判断点文本，来自 TaskSpec
     */
    judge: string;
    why?: string;
    /**
     * @minItems 3
     * @maxItems 8
     */
    sections:
      | [
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
        ]
      | [
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
        ]
      | [
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
        ]
      | [
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
        ]
      | [
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
        ]
      | [
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
          {
            id: string;
            title: string;
            body_md: string;
            /**
             * 该节内嵌的代码块；exercise 类型引用顶层 exercise 字段
             */
            runnable?: {
              kind: "demo" | "exercise";
              demo_code?: string;
            };
          },
        ];
    coach_note?: string;
  };
  exercise: {
    /**
     * v0 browser runtime supports JavaScript/TypeScript aliases; Go/Python move to the server sandbox phase.
     */
    language: "javascript" | "typescript" | "js" | "ts";
    starter_code: string;
    /**
     * 校验闭环必需物（定稿前必须真跑通全部测试），存储必填；仅服务端使用，下发投影中剥离
     */
    reference_solution: string;
    harness_version: number;
    /**
     * @minItems 3
     */
    tests: [
      {
        id: string;
        /**
         * 对用户函数的调用表达式
         */
        call: string;
        /**
         * 期望值（任意 JSON 类型）
         */
        expect: {
          [k: string]: any;
        };
        /**
         * 是否为判断点测试；全卷至少一条为 true
         */
        judge: boolean;
        label: string;
      },
      {
        id: string;
        /**
         * 对用户函数的调用表达式
         */
        call: string;
        /**
         * 期望值（任意 JSON 类型）
         */
        expect: {
          [k: string]: any;
        };
        /**
         * 是否为判断点测试；全卷至少一条为 true
         */
        judge: boolean;
        label: string;
      },
      {
        id: string;
        /**
         * 对用户函数的调用表达式
         */
        call: string;
        /**
         * 期望值（任意 JSON 类型）
         */
        expect: {
          [k: string]: any;
        };
        /**
         * 是否为判断点测试；全卷至少一条为 true
         */
        judge: boolean;
        label: string;
      },
      ...{
        id: string;
        /**
         * 对用户函数的调用表达式
         */
        call: string;
        /**
         * 期望值（任意 JSON 类型）
         */
        expect: {
          [k: string]: any;
        };
        /**
         * 是否为判断点测试；全卷至少一条为 true
         */
        judge: boolean;
        label: string;
      }[],
    ];
  };
  meta?: {
    created_at?: string;
    model?: string;
    tok_in?: number;
    tok_out?: number;
    /**
     * 校验重试次数，进质量看板
     */
    validation_attempts?: number;
  };
}
