/* This file is generated by scripts/typegen.mjs. Do not edit manually. */

/**
 * 用户个性化学习大纲。它决定接下来学什么，后续 content generation 只消费其中的 TaskSpec。
 */
export interface LearningOutline {
  schema_version: number;
  outline_id: string;
  goal: string;
  target_role: string;
  target_stack: string;
  level_band: string;
  duration_days: number;
  daily_minutes: number;
  summary: string;
  /**
   * @minItems 1
   */
  stages: [
    {
      id: string;
      title: string;
      goal: string;
      /**
       * @minItems 1
       */
      days: [number, ...number[]];
    },
    ...{
      id: string;
      title: string;
      goal: string;
      /**
       * @minItems 1
       */
      days: [number, ...number[]];
    }[],
  ];
  /**
   * @minItems 1
   */
  tasks: [
    {
      day_index: number;
      task_template_id: string;
      target_stack: string;
      level_band: string;
      title: string;
      judge: string;
      minutes: number;
    },
    ...{
      day_index: number;
      task_template_id: string;
      target_stack: string;
      level_band: string;
      title: string;
      judge: string;
      minutes: number;
    }[],
  ];
  meta?: {
    created_at?: string;
    model?: string;
    tok_in?: number;
    tok_out?: number;
  };
}
