/* This file is generated by scripts/typegen.mjs. Do not edit manually. */

/**
 * 学习大纲生成 run 的公开投影。
 */
export interface OutlineGenerationRun {
  run_id: string;
  status:
    | "accepted"
    | "queued"
    | "executing"
    | "waiting_tool"
    | "waiting_approval"
    | "succeeded"
    | "failed"
    | "expired"
    | "cancelled";
  outline_id?: string;
  error?: {
    code?: string;
    message?: string;
    [k: string]: any;
  };
}
