/* This file is generated by scripts/typegen.mjs. Do not edit manually. */

/**
 * POST /api/outline-generation-runs 的请求体。它允许用户信息和用户要求影响学习大纲，但不直接影响可复用 content_artifacts。
 */
export interface OutlineGenerationInput {
  goal: string;
  current_level: string;
  target_role: string;
  target_stack: string;
  daily_minutes?: number;
  duration_days?: number;
  preferences?: string[];
  constraints?: string[];
  background?: string;
}
