/* This file is generated by scripts/typegen.mjs. Do not edit manually. */

/**
 * GET /api/content-artifacts/{content_key} 下发给客户端的内容 artifact 投影。它明确剥离 exercise.reference_solution，只保留学习页需要展示和运行的字段。
 */
export interface PublicContentArtifact {
  schema_version: number;
  content_key: string;
  task_template_id: string;
  target_stack: string;
  level_band: string;
  content_version: number;
  prompt_version: number;
  review_status: "auto_ok" | "needs_review" | "human_ok" | "rejected";
  validation_attempts: number;
  lesson: {
    title: string;
    minutes: number;
    judge: string;
    why?: string;
    sections: {
      id: string;
      title: string;
      body_md: string;
      runnable?: {
        kind: "demo" | "exercise";
        demo_code?: string;
      };
    }[];
    coach_note?: string;
  };
  exercise: {
    language: "javascript" | "typescript" | "js" | "ts";
    starter_code: string;
    harness_version: number;
    tests: {
      id: string;
      call: string;
      expect: any;
      judge: boolean;
      label: string;
    }[];
  };
  meta?: {
    created_at?: string;
    model?: string;
    tok_in?: number;
    tok_out?: number;
    validation_attempts?: number;
  };
}
