/* This file is generated by scripts/typegen.mjs. Do not edit manually. */

/**
 * ReviewCompleted 事件 payload 主体（docs/event-catalog.md）。模型生成侧使用 review-output.schema.json；调用方在写事件前把 evidence_id 注入本 payload。
 */
export interface ReviewCompleted {
  /**
   * 调用方注入，不由模型生成
   */
  evidence_id: string;
  /**
   * 「你已经做到」——先肯定，与 UI 的 Review 结果屏一致
   *
   * @minItems 1
   */
  did: [string, ...string[]];
  /**
   * 当前最值得改的一个点（一次只改一个）
   */
  fix: string;
  /**
   * 下一步（只做这一件）
   */
  next: string;
  cap_delta: {
    /**
     * 对应画像 capabilities[].id（docs/learner-profile.md）
     */
    capability_id: string;
    /**
     * 0 未接触 / 1 看过 / 2 能解释 / 3 能实现 / 4 能教
     */
    from: number;
    /**
     * 一次 Review 至多 +1，投影层强制
     */
    to: number;
    /**
     * 用户可读的变化描述，如「看过 → 能解释」
     */
    label: string;
  };
  /**
   * 可选：本次发现的活跃误解
   */
  misconception?: {
    /**
     * 误解的一句话表述，如「把 failed 当成了终态可回退」
     */
    statement: string;
    /**
     * 建议用什么样的任务验证已纠正
     */
    planned_probe_hint?: string;
  };
  /**
   * 写给用户的记忆卡条目（完成态「今天我记住了你」展示）
   */
  memo: string;
  /**
   * 明日任务种子，任务生成 run 消费
   */
  next_task_seed: {
    title: string;
    minutes: number;
  };
}
