import { mkdir, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compileFromFile } from "json-schema-to-typescript";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const schemasDir = path.join(root, "schemas");
const outDir = path.join(root, "frontend", "src", "contracts");

const schemaFiles = (await readdir(schemasDir))
  .filter((file) => file.endsWith(".schema.json"))
  .sort();

await mkdir(outDir, { recursive: true });

const exports = [];
for (const schemaFile of schemaFiles) {
  const schemaPath = path.join(schemasDir, schemaFile);
  const outputFile = schemaFile.replace(".schema.json", ".ts");
  const ts = await compileFromFile(schemaPath, {
    bannerComment: "/* This file is generated by scripts/typegen.mjs. Do not edit manually. */",
    style: {
      semi: true,
      singleQuote: false,
      tabWidth: 2,
      trailingComma: "all",
    },
    unknownAny: false,
  });

  await writeFile(path.join(outDir, outputFile), ts);
  exports.push(`export * from "./${outputFile.replace(".ts", "")}";`);
}

await writeFile(
  path.join(outDir, "index.ts"),
  `${exports.join("\n")}\n`,
);
