{{- range $name, $workload := .Values.workloads }}
{{- if $workload.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lites.workloadName" (dict "root" $ "name" $name) }}
  labels:
    {{- include "lites.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
automountServiceAccountToken: false
{{- end }}
{{- end }}
